/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * calculadora2.java
 *
 * Created on 19-jun-2012, 22:38:53
 */
package Calcula;

/**
 *
 * @author bLacko
 */
public class calculadora2 extends javax.swing.JFrame {

    /** Creates new form calculadora2 */
    public calculadora2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        reslmbrec = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resfcrec = new javax.swing.JTextArea();
        vrf = new javax.swing.JTextField();
        vra = new javax.swing.JTextField();
        vrb = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        resztmrec = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        resBrec = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        resVprec = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        reszterec = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        resVgrec = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        reslmbgrec = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        reslmbrec.setColumns(5);
        reslmbrec.setEditable(false);
        reslmbrec.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        reslmbrec.setForeground(new java.awt.Color(153, 153, 255));
        reslmbrec.setRows(5);
        reslmbrec.setWrapStyleWord(true);
        reslmbrec.setFocusable(false);
        reslmbrec.setMaximumSize(new java.awt.Dimension(164, 94));
        jScrollPane3.setViewportView(reslmbrec);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 3, 14));
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Frecuencias de corte");

        resfcrec.setColumns(5);
        resfcrec.setEditable(false);
        resfcrec.setFont(new java.awt.Font("Eras Demi ITC", 0, 14));
        resfcrec.setForeground(new java.awt.Color(153, 153, 255));
        resfcrec.setRows(5);
        resfcrec.setWrapStyleWord(true);
        resfcrec.setFocusable(false);
        resfcrec.setMaximumSize(new java.awt.Dimension(164, 94));
        jScrollPane2.setViewportView(resfcrec);

        vrf.setFont(new java.awt.Font("Palatino Linotype", 1, 14));
        vrf.setForeground(new java.awt.Color(102, 0, 255));

        vra.setFont(new java.awt.Font("Palatino Linotype", 1, 14));
        vra.setForeground(new java.awt.Color(102, 0, 255));

        vrb.setFont(new java.awt.Font("Palatino Linotype", 1, 14));
        vrb.setForeground(new java.awt.Color(102, 0, 255));

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14));
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel11.setText("Frecuencia:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel9.setText("b:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setText(" a:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18));
        jLabel7.setText("cms");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18));
        jLabel10.setText("Ghz");

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18));
        jLabel8.setText("cms");

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 3, 14));
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Longitud de corte");

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 3, 14));
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("l.o. en la guia de onda");

        resztmrec.setColumns(5);
        resztmrec.setEditable(false);
        resztmrec.setFont(new java.awt.Font("Eras Demi ITC", 0, 14));
        resztmrec.setForeground(new java.awt.Color(153, 153, 255));
        resztmrec.setRows(5);
        resztmrec.setWrapStyleWord(true);
        resztmrec.setFocusable(false);
        resztmrec.setMaximumSize(new java.awt.Dimension(164, 94));
        jScrollPane8.setViewportView(resztmrec);

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 3, 14));
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("fACTOR DE FASE");

        resBrec.setColumns(5);
        resBrec.setEditable(false);
        resBrec.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        resBrec.setForeground(new java.awt.Color(153, 153, 255));
        resBrec.setRows(5);
        resBrec.setWrapStyleWord(true);
        resBrec.setFocusable(false);
        resBrec.setMaximumSize(new java.awt.Dimension(164, 94));
        jScrollPane4.setViewportView(resBrec);

        resVprec.setColumns(5);
        resVprec.setEditable(false);
        resVprec.setFont(new java.awt.Font("Eras Demi ITC", 0, 14));
        resVprec.setForeground(new java.awt.Color(153, 153, 255));
        resVprec.setRows(5);
        resVprec.setWrapStyleWord(true);
        resVprec.setFocusable(false);
        resVprec.setMaximumSize(new java.awt.Dimension(164, 94));
        jScrollPane7.setViewportView(resVprec);

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 3, 14));
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("Velocidad de grupo");

        reszterec.setColumns(5);
        reszterec.setEditable(false);
        reszterec.setFont(new java.awt.Font("Eras Demi ITC", 0, 14));
        reszterec.setForeground(new java.awt.Color(153, 153, 255));
        reszterec.setRows(5);
        reszterec.setWrapStyleWord(true);
        reszterec.setFocusable(false);
        reszterec.setMaximumSize(new java.awt.Dimension(164, 94));
        jScrollPane5.setViewportView(reszterec);

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 3, 14));
        jLabel12.setForeground(new java.awt.Color(0, 51, 204));
        jLabel12.setText("Velocidad de Fase");

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 3, 14));
        jLabel13.setForeground(new java.awt.Color(0, 51, 204));
        jLabel13.setText("imp. electrica");

        jLabel14.setFont(new java.awt.Font("Perpetua Titling MT", 3, 14));
        jLabel14.setForeground(new java.awt.Color(0, 51, 204));
        jLabel14.setText("imp. magnetica");

        resVgrec.setColumns(5);
        resVgrec.setEditable(false);
        resVgrec.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        resVgrec.setForeground(new java.awt.Color(153, 153, 255));
        resVgrec.setRows(5);
        resVgrec.setWrapStyleWord(true);
        resVgrec.setFocusable(false);
        resVgrec.setMaximumSize(new java.awt.Dimension(164, 94));
        jScrollPane9.setViewportView(resVgrec);

        reslmbgrec.setColumns(5);
        reslmbgrec.setEditable(false);
        reslmbgrec.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        reslmbgrec.setForeground(new java.awt.Color(153, 153, 255));
        reslmbgrec.setRows(5);
        reslmbgrec.setWrapStyleWord(true);
        reslmbgrec.setFocusable(false);
        reslmbgrec.setMaximumSize(new java.awt.Dimension(164, 94));
        jScrollPane10.setViewportView(reslmbgrec);

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Clean");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(4, 4, 4)
                        .addComponent(vrf, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(vrb, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(vra, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(192, 192, 192))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel14))
                                .addComponent(jLabel1))
                            .addComponent(jLabel13)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton1)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vrb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(vrf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                        .addComponent(jLabel12)
                                        .addGap(12, 12, 12))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .addContainerGap(22, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    double a, b, lim;
    int i, j;
    resfcrec.setText("");
    reslmbrec.setText("");
    resBrec.setText("");
    resVprec.setText("");
    reslmbgrec.setText("");
    resztmrec.setText("");
    reszterec.setText("");
    resVgrec.setText("");
    a = Double.parseDouble(vra.getText());
    b = Double.parseDouble(vrb.getText());
    lim = Double.parseDouble(vrf.getText());
    lim *= 1000000000;
    a /= 100;
    b /= 100;
    oper rec = new oper();
    for (i = 0; i < 1000; i++) {
        for (j = 0; j < 1000; j++) {
            rec.fcrec(a, b, i, j);
            if ((i == 0) && (j == 0)) {
            } else {
                if (rec.fc2 < lim) {
                    if ("".equals(resfcrec.getText())) {
                        resfcrec.append("fc (" + i + "," + j + ")" + " = " + rec.Redondear((rec.fc2) / 1000000000) + " Ghz");
                    } else {
                        resfcrec.append("\nfc (" + i + "," + j + ")" + " = " + rec.Redondear((rec.fc2) / 1000000000) + " Ghz");
                    }
                    rec.lmbrec(a, b, i, j);
                    if ("".equals(reslmbrec.getText())) {
                        reslmbrec.append("lc (" + i + "," + j + ")" + " = " + rec.Redondear(rec.lmb2) + " cms");
                    } else {
                        reslmbrec.append("\nlc (" + i + "," + j + ")" + " = " + rec.Redondear(rec.lmb2) + " cms");
                    }
                    rec.brec(lim, rec.fc2);
                    if ("".equals(resBrec.getText())) {
                        resBrec.append("B (" + i + "," + j + ")" + " = " + rec.Redondear(rec.B) + " rad/m");
                    } else {
                        resBrec.append("\nB (" + i + "," + j + ")" + " = " + rec.Redondear(rec.B) + " rad/m");
                    }
                    rec.vprec(lim, rec.fc2);
                    if ("".equals(resVprec.getText())) {
                        resVprec.append("Vp (" + i + "," + j + ")" + " = " + rec.Redondear(rec.Vp) + " m/s");
                    } else {
                        resVprec.append("\nVp (" + i + "," + j + ")" + " = " + rec.Redondear(rec.Vp) + " m/s");
                    }
                    rec.lmbgrec(rec.B);
                    if ("".equals(reslmbgrec.getText())) {
                        reslmbgrec.append("lg (" + i + "," + j + ")" + " = " + rec.Redondear(rec.lmbg*100) + " cms");
                    } else {
                        reslmbgrec.append("\nlg (" + i + "," + j + ")" + " = " + rec.Redondear(rec.lmbg*100) + " cms");
                    }
                    rec.zte(lim, rec.B);
                    if ("".equals(reszterec.getText())) {
                        reszterec.append("ZTe (" + i + "," + j + ")" + " = " + rec.Redondear(rec.te*10) + " Ohms");
                    } else {
                        reszterec.append("\nZTe (" + i + "," + j + ")" + " = " + rec.Redondear(rec.te*10) + " Ohms");
                    }
                    rec.ztm(lim, rec.fc2);
                    if ("".equals(resztmrec.getText())) {
                        resztmrec.append("ZTm (" + i + "," + j + ")" + " = " + rec.Redondear(rec.tm) + " Ohms");
                    } else {
                        resztmrec.append("\nZTm (" + i + "," + j + ")" + " = " + rec.Redondear(rec.tm) + " Ohms");
                    }
                    rec.Vpgrec(lim, rec.fc2);
                    if ("".equals(resVgrec.getText())) {
                        resVgrec.append("Vg (" + i + "," + j + ")" + " = " + rec.Redondear(rec.Vpg) + " m/s");
                    } else {
                        resVgrec.append("\nVg (" + i + "," + j + ")" + " = " + rec.Redondear(rec.Vpg) + " m/s");
                    }
                }
            }
        }
    }
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    resfcrec.setText("  ");
    reslmbrec.setText("  ");
    resztmrec.setText("  ");
    reszterec.setText("  ");
    resVprec.setText("  ");
    resVgrec.setText("  ");
    resBrec.setText("  ");
    reslmbgrec.setText("  ");
    
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new calculadora2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea resBrec;
    private javax.swing.JTextArea resVgrec;
    private javax.swing.JTextArea resVprec;
    private javax.swing.JTextArea resfcrec;
    private javax.swing.JTextArea reslmbgrec;
    private javax.swing.JTextArea reslmbrec;
    private javax.swing.JTextArea reszterec;
    private javax.swing.JTextArea resztmrec;
    private javax.swing.JTextField vra;
    private javax.swing.JTextField vrb;
    private javax.swing.JTextField vrf;
    // End of variables declaration//GEN-END:variables
}
