/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Interpolacion.java
 *
 * Created on 05-mar-2013, 7:47:54
 */
package matriz;

/**
 *
 * @author bLacko
 */
public class Interpolacion extends javax.swing.JFrame {

    /** Creates new form Interpolacion */
    public Interpolacion() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        func = new javax.swing.JTable();
        linea = new javax.swing.JRadioButton();
        cuadra = new javax.swing.JRadioButton();
        cubito = new javax.swing.JRadioButton();
        encuentra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        resultado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        resultado1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        resultado2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        var = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        func.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", ""},
                {"", ""},
                {"", ""},
                {"", ""},
                {"", ""},
                {"", ""},
                {null, null}
            },
            new String [] {
                "X", "Funcion de (x)"
            }
        ));
        jScrollPane1.setViewportView(func);

        buttonGroup1.add(linea);
        linea.setText("Lineal");

        buttonGroup1.add(cuadra);
        cuadra.setText("Cuadratica");

        buttonGroup1.add(cubito);
        cubito.setSelected(true);
        cubito.setText("Cubica");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setText("Tipo de Interpolacion");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setText("Valor a Encontrar");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("Resultado:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setText("Resultado:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setText("Resultado:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setText("Variables en la tabla");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel7.setText("Metodo Directo");

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(resultado1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(resultado2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(linea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cuadra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cubito))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(var)
                                    .addComponent(encuentra, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(linea)
                            .addComponent(cuadra)
                            .addComponent(cubito))
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(encuentra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resultado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resultado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(var, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(jButton2)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    double u=0, p=0, o=0;
    double m=0,n=0,a=0,b=0;
    double ecua=0;
    p= Double.parseDouble(encuentra.getText());
     int varr= Integer.parseInt(var.getText());
   
    if(linea.isSelected()==true)
    {
    double temp=1, tempo=1, tempi=0;
    double prires;
    for(int i=0; i<=varr;i++)
    {
    u= Double.parseDouble(func.getValueAt(i, 0).toString());
    o= Double.parseDouble(func.getValueAt(i+1, 0).toString());
    m= (u+o)/2;
    if(m<=0)
    {
    if(m<=p && m>=o && m<=u)
    {
    a= Double.parseDouble(func.getValueAt(i, 1).toString());
    b= Double.parseDouble(func.getValueAt(i+1, 1).toString());
    break; 
    }
    }    
    if(m>=p && m<=o && m>=u)
    {
    a= Double.parseDouble(func.getValueAt(i, 1).toString());
    b= Double.parseDouble(func.getValueAt(i+1, 1).toString());
    break; 
    }
    }
    //----- Pivote
    tempi=temp;
    temp=tempi/temp;
    u=(u/tempi);
    a=(a/tempi);
    //--------------
    prires=tempo;
    tempo=((-1*prires)*temp)+tempo;
    o= ((-1*prires)*u)+o;
    b= ((-1*prires)*a)+b;
    
    //----- Pivote
    tempi=o;
    tempo= (tempo/tempi);
    o=o/tempi;
    b=b/tempi;
    //--------------
    prires= u;
    temp= ((-1*prires)*tempo)+temp;
    u= ((-1*prires)*o)+u;
    a= ((-1*prires)*b)+a;
    //------ GAUSS-JORDAN!!!!!!!!!  
    ecua=a+(b*p);
    resultado.setText(String.valueOf(ecua));
    }

    if(cuadra.isSelected()==true)
    {
        double c=0,u1=1,e1=1,o1=1,e=0 ,ii=0;
        double e2=0, u2=0, o2=0, tempi=0;
       
     
    for(int i=0; i<=varr;i++)
    {  
    u= Double.parseDouble(func.getValueAt(i, 0).toString());
    o= Double.parseDouble(func.getValueAt(i+1, 0).toString());
    m= (u+o)/2;
    if(m<=0)
    {
       if(m<=p && m>=o && m<=u)
    {
    a= Double.parseDouble(func.getValueAt(i, 1).toString());
    b= Double.parseDouble(func.getValueAt(i+1, 1).toString());
        
    if(i==0)
    { 
    e= Double.parseDouble(func.getValueAt(i+2, 0).toString());
    c= Double.parseDouble(func.getValueAt(i+2, 1).toString());
    }
    else
    {
      e= Double.parseDouble(func.getValueAt(i-1, 0).toString());   
      c= Double.parseDouble(func.getValueAt(i-1, 1).toString());  
    }
    break; 
    } 
    }
    if(m>=p && m<=o && m>=u)
    {
    a= Double.parseDouble(func.getValueAt(i, 1).toString());
    b= Double.parseDouble(func.getValueAt(i+1, 1).toString());
        
    if(i==0)
    { 
    e= Double.parseDouble(func.getValueAt(i+2, 0).toString());
    c= Double.parseDouble(func.getValueAt(i+2, 1).toString());
    }
    else
    {
      e= Double.parseDouble(func.getValueAt(i-1, 0).toString());   
      c= Double.parseDouble(func.getValueAt(i-1, 1).toString());  
    }
    break; 
    }
    }
    e2=e*e;
    u2=u*u;
    o2=o*o;
    //----- Pivote
    ii= e1;
    e1=e1/ii;
    e=e/ii;
    e2=e2/ii;
    c=c/ii;
    //--------------Gauss-jordan
    
    tempi=u1;
    u1=((-1*tempi)*e1)+u1;
    u=((-1*tempi)*e)+u;
    u2=((-1*tempi)*e2)+u2;
    a=((-1*tempi)*c)+a;
    
    tempi = o1;
    o1=((-1*tempi)*e1)+o1;
    o=((-1*tempi)*e)+o;
    o2=((-1*tempi)*e2)+o2;
    b=((-1*tempi)*c)+b;
    
    
    //--------------
    ii=u;
    u1=u1/ii;
    u=u/ii;
    u2=u2/ii;
    a=a/ii;
    //--------------Gauss-jordan
    tempi=e;
    e1=((-1*tempi)*u1)+e1;
    e=((-1*tempi)*u)+e;
    e2=((-1*tempi)*u2)+e2;
    c=((-1*tempi)*a)+c;
    
    tempi = o;
    o1=((-1*tempi)*u1)+o1;
    o=((-1*tempi)*u)+o;
    o2=((-1*tempi)*u2)+o2;
    b=((-1*tempi)*a)+b;
    //--------------
    ii=o2;
    o1=o1/ii;
    o=o/ii;
    o2=o2/ii;
    b=b/ii;
    //--------------Gauss-jordan
    tempi=e2;
    e1=((-1*tempi)*o1)+e1;
    e=((-1*tempi)*o)+e;
    e2=((-1*tempi)*o2)+e2;
    c=((-1*tempi)*b)+c;
    
    tempi=u2;
    u1=((-1*tempi)*o1)+u1;
    u=((-1*tempi)*o)+u;
    u2=((-1*tempi)*o2)+u2;
    a=((-1*tempi)*b)+a;
    
    ecua=c+(a*p)+(b*p*p);
    resultado1.setText(String.valueOf(ecua));
    }
    
    if(cubito.isSelected()==true)
    {
        double e=0, c=0, ii=0, d=0;
        double e1=1, e2=0,e3=0;
        double u1=1, u2=0,u3=0;
        double o1=1, o2=0,o3=0;
        double ii1=1, ii2=0,ii3=0;
        double piv, tempo;
        
    for(int i=0; i<=varr;i++)
    {  
    u= Double.parseDouble(func.getValueAt(i, 0).toString());
    o= Double.parseDouble(func.getValueAt(i+1, 0).toString());
    m= (u+o)/2;
    if(m<=0)
    {
    if(m<=p && m>=o && m<=u)
    {
    a= Double.parseDouble(func.getValueAt(i, 1).toString());
    b= Double.parseDouble(func.getValueAt(i+1, 1).toString());
        
    if(i==0)
    { 
    e= Double.parseDouble(func.getValueAt(i+2, 0).toString());
    c= Double.parseDouble(func.getValueAt(i+2, 1).toString());
    ii= Double.parseDouble(func.getValueAt(i+3, 0).toString());
    d= Double.parseDouble(func.getValueAt(i+3, 1).toString());
    }
    else
    {
      e= Double.parseDouble(func.getValueAt(i-1, 0).toString());   
      c= Double.parseDouble(func.getValueAt(i-1, 1).toString());
      ii= Double.parseDouble(func.getValueAt(i+2, 0).toString());
      d= Double.parseDouble(func.getValueAt(i+2, 1).toString());
    }
    break; 
    }
    }
    if(m>=p && m<=o && m>=u)
    {
    a= Double.parseDouble(func.getValueAt(i, 1).toString());
    b= Double.parseDouble(func.getValueAt(i+1, 1).toString());
        
    if(i==0)
    { 
    e= Double.parseDouble(func.getValueAt(i+2, 0).toString());
    c= Double.parseDouble(func.getValueAt(i+2, 1).toString());
    ii= Double.parseDouble(func.getValueAt(i+3, 0).toString());
    d= Double.parseDouble(func.getValueAt(i+3, 1).toString());
    }
    else
    {
      e= Double.parseDouble(func.getValueAt(i-1, 0).toString());   
      c= Double.parseDouble(func.getValueAt(i-1, 1).toString());
      ii= Double.parseDouble(func.getValueAt(i+2, 0).toString());
      d= Double.parseDouble(func.getValueAt(i+2, 1).toString());
    }
    break; 
    }
    }
    e2=e*e;
    u2=u*u;
    o2=o*o;
    ii2=ii*ii;
    
    e3=e*e*e;
    u3=u*u*u;
    o3=o*o*o;
    ii3=ii*ii*ii;
    
    //----- Pivote
    piv= e1;
    e1=e1/piv;
    e=e/piv;
    e2=e2/piv;
    e3=e3/piv;
    c=c/piv;
    //--------------
    tempo= u1;
    u1=((-1*tempo)*e1)+u1;
    u=((-1*tempo)*e)+u;
    u2=((-1*tempo)*e2)+u2;
    u3=((-1*tempo)*e3)+u3;
    a=((-1*tempo)*c)+a;
    
    tempo= o1;
    o1=((-1*tempo)*e1)+o1;
    o=((-1*tempo)*e)+o;
    o2=((-1*tempo)*e2)+o2;
    o3=((-1*tempo)*e3)+o3;
    b=((-1*tempo)*c)+b;
    
    tempo= ii1;
    ii1=((-1*tempo)*e1)+ii1;
    ii=((-1*tempo)*e)+ii;
    ii2=((-1*tempo)*e2)+ii2;
    ii3=((-1*tempo)*e3)+ii3;
    d=((-1*tempo)*c)+d;
    //----- Pivote
    piv= u;
    u1=u1/piv;
    u=u/piv;
    u2=u2/piv;
    u3=u3/piv;
    a=a/piv;
    //--------------
    tempo= e;
    e1=((-1*tempo)*u1)+e1;
    e=((-1*tempo)*u)+e;
    e2=((-1*tempo)*u2)+e2;
    e3=((-1*tempo)*u3)+e3;
    c=((-1*tempo)*a)+c;
    
    tempo= o;
    o1=((-1*tempo)*u1)+o1;
    o=((-1*tempo)*u)+o;
    o2=((-1*tempo)*u2)+o2;
    o3=((-1*tempo)*u3)+o3;
    b=((-1*tempo)*a)+b;
    
    tempo= ii;
    ii1=((-1*tempo)*u1)+ii1;
    ii=((-1*tempo)*u)+ii;
    ii2=((-1*tempo)*u2)+ii2;
    ii3=((-1*tempo)*u3)+ii3;
    d=((-1*tempo)*a)+d;
    
    //----- Pivote
    piv= o2;
    o1=o1/piv;
    o=o/piv;
    o2=o2/piv;
    o3=o3/piv;
    b=b/piv;
    //--------------
    tempo= e2;
    e1=((-1*tempo)*o1)+e1;
    e=((-1*tempo)*o)+e;
    e2=((-1*tempo)*o2)+e2;
    e3=((-1*tempo)*o3)+e3;
    c=((-1*tempo)*b)+c;
    
    tempo= u2;
    u1=((-1*tempo)*o1)+u1;
    u=((-1*tempo)*o)+u;
    u2=((-1*tempo)*o2)+u2;
    u3=((-1*tempo)*o3)+u3;
    a=((-1*tempo)*b)+a;
    
    tempo= ii2;
    ii1=((-1*tempo)*o1)+ii1;
    ii=((-1*tempo)*o)+ii;
    ii2=((-1*tempo)*o2)+ii2;
    ii3=((-1*tempo)*o3)+ii3;
    d=((-1*tempo)*b)+d;
     //----- Pivote
    piv= ii3;
    ii1=ii1/piv;
    ii=ii/piv;
    ii2=ii2/piv;
    ii3=ii3/piv;
    d=d/piv;
    //--------------
    
    tempo= e3;
    e1=((-1*tempo)*ii1)+e1;
    e=((-1*tempo)*ii)+e;
    e2=((-1*tempo)*ii2)+e2;
    e3=((-1*tempo)*ii3)+e3;
    c=((-1*tempo)*d)+c;
    
    tempo= u3;
    u1=((-1*tempo)*ii1)+u1;
    u=((-1*tempo)*ii)+u;
    u2=((-1*tempo)*ii2)+u2;
    u3=((-1*tempo)*ii3)+u3;
    a=((-1*tempo)*d)+a;
    
    tempo= o3;
    o1=((-1*tempo)*ii1)+o1;
    o=((-1*tempo)*ii)+o;
    o2=((-1*tempo)*ii2)+o2;
    o3=((-1*tempo)*ii3)+o3;
    b=((-1*tempo)*d)+b;
    //-----------------
    
    ecua=c+(a*p)+(b*p*p)+(d*p*p*p);
    
    resultado2.setText(String.valueOf(ecua));
  
    
    
    }
    
    
   
    
    
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    resultado.setText("");
    resultado1.setText("");
    resultado2.setText("");
}//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interpolacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interpolacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interpolacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interpolacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Interpolacion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cuadra;
    private javax.swing.JRadioButton cubito;
    private javax.swing.JTextField encuentra;
    private javax.swing.JTable func;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton linea;
    private javax.swing.JTextField resultado;
    private javax.swing.JTextField resultado1;
    private javax.swing.JTextField resultado2;
    private javax.swing.JTextField var;
    // End of variables declaration//GEN-END:variables
}
