/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * textarea.java
 *
 * Created on 06-may-2012, 22:17:05
 */
/**
 *
 * @author bLacko
 */
import java.awt.*;

import javax.swing.JFrame;

import javax.swing.JScrollPane;

import javax.swing.JTextArea;

public class textarea extends javax.swing.JFrame {
String text;
int cuenta;
    /** Creates new form textarea */
    public textarea() {
   


//Método para cambiar la decoración de la ventana en sí,

//si ponemos el valor en falso la ventana se verá de la forma predeterminada de Windows

JFrame.setDefaultLookAndFeelDecorated(true);


//creamos el JFrame principal donde agregaremos el resto de objetos

JFrame frame = new JFrame ("JTextArea Test");

frame.setLayout (new FlowLayout ());

frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);


String text = "Un objeto JTextArea es una área multilínea para escribir texto. "

+ "Se puede cambiar el número de líneas que se mostrarán, "

+ "y también el numero de columnas. Puedes cambiar las fuentes y tamaños de letras. "

+ "Y puedes agregar tu TextArea en un JScrollPane para poder mover las zonas de texto." ;


//creamos un area de texto normal no redimensionable

JTextArea textAreal = new JTextArea(text,20,10);

textAreal.setPreferredSize(new Dimension (10,100));

//creamos otra área de texto con un JScrollPane, sólo es agregado

JTextArea textArea2 = new JTextArea(text,20,10);

JScrollPane scroll = new JScrollPane(textArea2);

frame.getContentPane().add(scroll, BorderLayout.CENTER);

frame.add(scroll);


//El método setLineWrap lo que hace es ordenar las palabras para que no se salgan de los márgenes,

//si lo desactivamos(false), el texto se escribirá hacia el lado(en una línea) y no se vería todo si el //texto es muy largo

textAreal.setLineWrap (true);

textArea2.setLineWrap (true);

textAreal.setWrapStyleWord(true);

textArea2.setWrapStyleWord(true);


//agregamos los area de texto al frame principal,

//nota: el textArea2 está dentro de un JScrollPane, por eso éste es el que agregamos al frame

frame.add(textAreal);

frame.add(scroll);
     
//el metodo pack sirve para dejar todo dentro del frame

frame.pack();


//y finalmente el metodo setVisible es para que se visualice la ventana

frame.setVisible(true) ;

        
        
        
        
        
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        negro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        area2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        negro.setBackground(new java.awt.Color(0, 153, 51));
        negro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        negro.setForeground(new java.awt.Color(204, 255, 204));
        negro.setText("Negro");
        negro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negroActionPerformed(evt);
            }
        });

        area1.setBackground(new java.awt.Color(153, 255, 153));
        area1.setColumns(20);
        area1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        area1.setForeground(new java.awt.Color(0, 153, 0));
        area1.setRows(5);
        jScrollPane1.setViewportView(area1);

        area2.setBackground(new java.awt.Color(0, 153, 0));
        area2.setColumns(20);
        area2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        area2.setForeground(new java.awt.Color(102, 255, 153));
        area2.setRows(5);
        jScrollPane2.setViewportView(area2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("TextArea");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(negro, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(negro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void negroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negroActionPerformed
// TODO add your handling code here:
    text = area1.getText();
    area2.setText(text);
    
}//GEN-LAST:event_negroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(textarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(textarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(textarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(textarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new textarea().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area1;
    private javax.swing.JTextArea area2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton negro;
    // End of variables declaration//GEN-END:variables
}
