/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JOptionPane;

/**
 *
 * @author Vazquez Aguilar
 */
public class puntoventa extends javax.swing.JFrame {
    Double magnaact=11.25;
    Double premiumact=11.81;
    Double dieselact=11.61;
    int opcion=0;
    /**
     * Creates new form puntoventa
     */
    public puntoventa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        etiptoventa = new javax.swing.JLabel();
        eticajero = new javax.swing.JLabel();
        etiencaja = new javax.swing.JLabel();
        txtlitros = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        btnmagna = new javax.swing.JButton();
        btnpremium = new javax.swing.JButton();
        btndiesel = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        etimagna = new javax.swing.JLabel();
        etipremium = new javax.swing.JLabel();
        etidiesel = new javax.swing.JLabel();
        btncobrar = new javax.swing.JButton();
        btnabrir = new javax.swing.JButton();
        btncerrar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        etiactualizar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Punto de Venta:");

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Cajero:");

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("En caja:");

        etiptoventa.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        etiptoventa.setText("AQUI VA UN TEXTO");

        eticajero.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        eticajero.setText(" ");

        etiencaja.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        etiencaja.setText("0.00");

        txtlitros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtlitros.setText("0.0");
        txtlitros.setEnabled(false);

        txtprecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtprecio.setText("0.00");
        txtprecio.setEnabled(false);

        btnmagna.setBackground(new java.awt.Color(0, 102, 0));
        btnmagna.setForeground(new java.awt.Color(255, 255, 255));
        btnmagna.setText("MAGNA");
        btnmagna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmagnaActionPerformed(evt);
            }
        });

        btnpremium.setBackground(new java.awt.Color(204, 0, 0));
        btnpremium.setForeground(new java.awt.Color(255, 255, 255));
        btnpremium.setText("PREMIUM");
        btnpremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpremiumActionPerformed(evt);
            }
        });

        btndiesel.setBackground(new java.awt.Color(0, 0, 0));
        btndiesel.setForeground(new java.awt.Color(255, 255, 255));
        btndiesel.setText("DIESEL");
        btndiesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndieselActionPerformed(evt);
            }
        });

        btnactualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnactualizar.setText("Act. Precios");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Litros");

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Precio ($)");

        etimagna.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 11)); // NOI18N
        etimagna.setText("$ Litro");

        etipremium.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 11)); // NOI18N
        etipremium.setText("$ Litro");

        etidiesel.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 11)); // NOI18N
        etidiesel.setText("$ Litro");

        btncobrar.setText("Cobrar");
        btncobrar.setEnabled(false);
        btncobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncobrarActionPerformed(evt);
            }
        });

        btnabrir.setText("Abrir Turno");
        btnabrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabrirActionPerformed(evt);
            }
        });

        btncerrar.setText("Cerrar Turno");
        btncerrar.setEnabled(false);
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        btnsalir.setText("Cerrar pto. de venta");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        etiactualizar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 11)); // NOI18N
        etiactualizar.setText("Solo Admin.");

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel4.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(etimagna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmagna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtlitros)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eticajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiptoventa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(etipremium, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnpremium, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(txtprecio, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(etidiesel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btndiesel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnactualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(etiactualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btncobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etiencaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnabrir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(etiptoventa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eticajero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(etiencaja)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlitros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncobrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnpremium)
                        .addComponent(btndiesel)
                        .addComponent(btnactualizar))
                    .addComponent(btnmagna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etimagna)
                    .addComponent(etipremium)
                    .addComponent(etidiesel)
                    .addComponent(etiactualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnabrir)
                    .addComponent(btnsalir)
                    .addComponent(btncerrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnabrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabrirActionPerformed
        String empleado=JOptionPane.showInputDialog(null,"Ingrese su Nombre");
        String contrasenia=JOptionPane.showInputDialog(null,"Ingrese su Contraseña");
        if (empleado.equals("Jose Juan")==true && contrasenia.equals("12345")==true)
        {
        opcion=1;
        btncobrar.setEnabled(true);
        btndiesel.setEnabled(true);
        btnmagna.setEnabled(true);
        btnpremium.setEnabled(true);
        eticajero.setText(empleado);
        txtlitros.setEnabled(true);
        btnabrir.setEnabled(false);
        btncerrar.setEnabled(true);
        }
        if (empleado.equals("Juan Jose")==true && contrasenia.equals("23456")==true)
        {
        opcion=1;
        btncobrar.setEnabled(true);
        btndiesel.setEnabled(true);
        btnmagna.setEnabled(true);
        btnpremium.setEnabled(true);
        eticajero.setText(empleado);
        txtlitros.setEnabled(true);
        btnabrir.setEnabled(false);
        btncerrar.setEnabled(true);
        }
        if (empleado.equals("Juan Pedro")==true && contrasenia.equals("34567")==true)
        {
        opcion=1;
        btncobrar.setEnabled(true);
        btndiesel.setEnabled(true);
        btnmagna.setEnabled(true);
        btnpremium.setEnabled(true);
        eticajero.setText(empleado);
        txtlitros.setEnabled(true);
        btnabrir.setEnabled(false);
        btncerrar.setEnabled(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnabrirActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        btncobrar.setEnabled(false);
        eticajero.setText("");
        etiencaja.setText("0.00");
        txtlitros.setText("0.0");
        txtprecio.setText("0.00");
        txtlitros.setEnabled(false);
        btnabrir.setEnabled(true);
        btncerrar.setEnabled(false);
        opcion=0;
        // TODO add your handling code here:
    }//GEN-LAST:event_btncerrarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        if (opcion!=1)
        {
        dispose();
        }
        else
        {
        JOptionPane.showMessageDialog(null,"¡Por favor cierre su turno antes de salir de la caja!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnmagnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmagnaActionPerformed
        double magna=Double.parseDouble(txtlitros.getText());
        double precmagna=magnaact;
        double totmagna=magna*precmagna;
        txtprecio.setText(String.valueOf(totmagna));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmagnaActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        String admincont=JOptionPane.showInputDialog(null,"Ingrese llave de Administrador");
        if (admincont.equals("mifechadenacimiento")==true)
        {
        String magnaactu=JOptionPane.showInputDialog(null,"Ingrese el aumento a la gasolina Magna");
        String premiumactu=JOptionPane.showInputDialog(null,"Ingrese el aumento a la gasolina Premium");
        String dieselactu=JOptionPane.showInputDialog(null,"Ingrese el aumento al diesel");
        magnaact=magnaact+Double.parseDouble(magnaactu);
        premiumact=premiumact+Double.parseDouble(premiumactu);
        dieselact=dieselact+Double.parseDouble(dieselactu);
        }
        else
        {
        JOptionPane.showMessageDialog(null,"Llave de administrador incorrecta ");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnpremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpremiumActionPerformed
        double premium=Double.parseDouble(txtlitros.getText());
        double precpremium=premiumact;
        double totpremium=premium*precpremium;
        txtprecio.setText(String.valueOf(totpremium));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpremiumActionPerformed

    private void btndieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndieselActionPerformed
        double diesel=Double.parseDouble(txtlitros.getText());
        double precdiesel=dieselact;
        double totdiesel=diesel*precdiesel;
        txtprecio.setText(String.valueOf(totdiesel));
        // TODO add your handling code here:
    }//GEN-LAST:event_btndieselActionPerformed

    private void btncobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncobrarActionPerformed
        double encaja=Double.parseDouble(txtprecio.getText());
        double totencaja=Double.parseDouble(etiencaja.getText());
        totencaja=totencaja+encaja;
        etiencaja.setText(String.valueOf(totencaja));
        txtlitros.setText("0.0");
        txtprecio.setText("0.00");
        // TODO add your handling code here:
    }//GEN-LAST:event_btncobrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(puntoventa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(puntoventa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(puntoventa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(puntoventa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new puntoventa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnabrir;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btncobrar;
    private javax.swing.JButton btndiesel;
    private javax.swing.JButton btnmagna;
    private javax.swing.JButton btnpremium;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel etiactualizar;
    private javax.swing.JLabel eticajero;
    private javax.swing.JLabel etidiesel;
    private javax.swing.JLabel etiencaja;
    private javax.swing.JLabel etimagna;
    private javax.swing.JLabel etipremium;
    private javax.swing.JLabel etiptoventa;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtlitros;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
